version: '3.7'
services:
  recipes:
    build: .
    environment:
      TYPEORM_HOST: db
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: recipes-test
      POSTGRES_USER: penguin-test
      POSTGRES_PASSWORD: penguin-test
